### ISSUE TITLE
How do I have buildspecs in subdirectories?

### ISSUE THREAD

**Issue by mpeckWhisker** [awslabs/aws-codebuild-multiple-buildspec#1]
I have a mono-repo with multiple projects in it.  I want to put the buildspec for each inside their top-level directory, and not at the root of the entire repo.

I can't find a way to make that work, as putting a path before the name of the buildspec file fails.

Can you show me a way to do this?

**Comment by mledom** [comment]
@mpeckWhisker did you ever figure out how to do this?

**Comment by mpeckWhisker** [comment]
I did finally find it.  It's described here:

https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec-ref-name-storage

I had banged my head on it for a while, before finally finding this.  I got it to work in the tests I was doing.

**Comment by abhilashshettigar** [comment]
@mpeckWhisker can you show what script you made or a sample using multiple build spec file in same Dir
