### ISSUE TITLE
Conditional statements in buildspec.yml

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [awslabs/aws-codebuild-multiple-buildspec#2]
Hi,

Would somebody be able to provide an example on how to use Conditional statements such as "if else statements" in a buildspec.yml.

Thanks in advance

**Comment by ktwbc** [comment]
```
   build:
     commands:
       - echo "${CODEBUILD_BUILD_ARN}"
       - |
         if expr "${CODEBUILD_BUILD_ARN}" : ".*build/MyProjectDev-" >/dev/null; then
           yarn run build-dev;
         fi
       - |
         if expr "${CODEBUILD_BUILD_ARN}" : ".*build/MyProject-" >/dev/null; then
           yarn run build-prod;
         fi
```

This is in a 0.2 version of buildspec.yml but we're just testing the ARN from the Codebuild process itself for a substring, and based on that running a different build command. This uses multiline capability of the yaml file

Example Arn that we're evaluating
 arn:aws:codebuild:us-east-1:123456789012:build/MyProject-build:7a2a906c-9e4b-4ac5-93a8-1fb5b447b5f0

**Comment by payne911** [comment]
@ktwbc works great, but is it possible to get an `if` within an `if` ?
And what about comments within those `if` statements ?

I'm trying to get different path of execution based on whether or not it is a PROD environment build.

```
      # SonarScanner for non-prod environments
      - |
        if [ "$BUILD_ENV" = "notprod" ] ; then
          # Downloading SonarScanner
          wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip ;
          unzip ./sonar-scanner-cli-4.2.0.1873-linux.zip ;
          export PATH=$PATH:/sonar-scanner-cli-4.2.0.1873-linux/bin/ ;
          # Executing SonarScanner
          mvn sonar:sonar -Dsonar.login=$SonarLogin -Dsonar.host.url=$SonarHostUrl -Dsonar.projectKey=$SonarProjectKey ;
          # Printing the Result Report
          sleep 5 ;
          curl http://ec2-xxx.ca-central-1.compute.amazonaws.com/api/qualitygates/project_status?projectKey=$SonarProjectKey >result.json ;
          cat result.json ;
          # Conditional failure of the build
          if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then
            $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;
          fi
        fi
```

**Comment by ktwbc** [comment]
@payne911 honestly just save yourself some hassle and build out a regular bash script as a separate file and call it from buildspec.yml

Example if you put all your bash code into a file in your repo under /aws/myscript.sh then chmod a+x before you check it in, then all you have to do is:

  pre_build:
    commands:
      - cp aws/* /usr/local/bin/

And now you can just call your script in the commands:
  build:
    commands:
      - myscript.sh

now that you're in your own bash instead of their buildspec format it makes all that easier and you still have access to all the environment variables. One word of warning. setting any new variables like export MY_VAR= whatever in your separated bash won't be passed back to buildspec to be used later.

**Comment by payne911** [comment]
Okay.
What about modifying some variables such as `$CODEBUILD_BUILD_SUCCEEDING` within the script?
Thanks for your reply, by the way. :)

**Comment by omerfsen** [comment]
If you export it within (myscript.sh) script it will be inherited from codebuild bash shell too

**myscript.sh:**
```bash
#!/bin/bash
export CODEBUILD_BUILD_SUCCEEDING=true
```
source ./myscript.sh

echo ${CODEBUILD_BUILD_SUCCEEDING} 


Use source instead of "."

**Comment by adv4000** [comment]
This simple if else didn't worked for me on CodeBuild Ubuntu using `aws/codebuild/standard:7.0`:

```
  - |
    if [[ "$OLD_IMAGE" == "$NEW_IMAGE" ]]; then
      echo "Same Image being deployed"
    else
      echo "New Image being deployed"
    fi
```
After switch to AmazonLinux Image: `aws/codebuild/amazonlinux2-x86_64-standard:5.0` all worked fine.

**Comment by vhajdukd** [comment]
> This simple if else didn't worked for me on CodeBuild Ubuntu using `aws/codebuild/standard:7.0`:
> 
> ```
>   - |
>     if [[ "$OLD_IMAGE" == "$NEW_IMAGE" ]]; then
>       echo "Same Image being deployed"
>     else
>       echo "New Image being deployed"
>     fi
> ```
> 
> After switch to AmazonLinux Image: `aws/codebuild/amazonlinux2-x86_64-standard:5.0` all worked fine.

This doesnt work on standard:7.0 coz it's ubuntu and for w/e reason AWS set sh as default shell for it despite bash being available. But you have to explicitly say it to use bash via env.shell..

AWS please some consistency :( :pray:
